name: Sync NODE repos

on:
  push:
    branches:
      - main

jobs:
  mirror-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone bare mirror
        run: |
          git clone --mirror https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NIXINX.git repo-mirror

      - name: Push to NODE-HTLeamington
        run: |
          cd repo-mirror
          git remote add leamington https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-HTLeamington.git
          git push --mirror leamington

      - name: Push to NODE-HTWindsor
        run: |
          cd repo-mirror
          git remote add windsor https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-HTWindsor.git
          git push --mirror windsor

      - name: Push to NODE-ElPatron
        run: |
          cd repo-mirror
          git remote add elpatron https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-ElPatron.git
          git push --mirror elpatron
